config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  post 'stocks_update', to: 'stocks#update'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :user_stocks
    has_many :users, through: :user_stocks

    validates :name, :ticker, presence: true

    def self.new_lookup(ticker)
        client = IEX::Api::Client.new(
            publishable_token: Rails.application.credentials.iex_cloud[:sandbox_api_key],
            endpoint: 'https://sandbox.iexapis.com/v1'
          )
        begin
            new(ticker: ticker, name: client.company(ticker).company_name, last_price: client.price(ticker))
        rescue => exception
            return nil
        end
    end

    def self.check_db(ticker)
        find_by(ticker: ticker)
    end

    def self.update_prices(ticker)
        client = IEX::Api::Client.new(
            publishable_token: Rails.application.credentials.iex_cloud[:sandbox_api_key],
            endpoint: 'https://sandbox.iexapis.com/v1'
          )
          client.price(ticker)
    end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def under_stock_limit?
    stocks.count < 10
  end

  def already_tracked?(ticker)
    stock = Stock.check_db(ticker)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def can_track_stock?(ticker)
    under_stock_limit? && !already_tracked?(ticker)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def self.search(param)
    param.strip!
    response = (first_name_search(param) + last_name_search(param) + email_search(param)).uniq
    return nil unless response
    response
  end

  def self.first_name_search(param)
    matches('first_name', param)
  end

  def self.last_name_search(param)
    matches('last_name', param)
  end

  def self.email_search(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(user_id)
    !self.friends.where(id: user_id).exists?
  end

  def friend_since(friend_id)
    user = self.friendships.where(friend_id: friend_id).first
    user.created_at 
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

    def create
        friend = User.find(params[:friend])
        current_user.friends << friend
        flash[:notice] = "You are now following #{friend.full_name}"
        redirect_to my_friends_path
    end

    def destroy
        friend = User.find(params[:id])
        friendship = Friendship.where(user_id: current_user.id, friend_id: friend.id).first
        friendship.destroy
        flash[:alert] = "You are no longer following #{friend.full_name}"
        redirect_to my_friends_path
    end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    respond_to :html, :json

    def search
        if params[:stock].present?
            @stock = Stock.new_lookup(params[:stock])
            if @stock
                respond_to do |format|
                    format.js { render partial: 'users/result.js' }
                end
            else
                respond_to do |format|
                    flash.now[:alert] = "Please enter a valid ticker symbol to search"
                    format.js { render partial: 'users/result.js' }
                    # render 'users/my_portfolio'
                end
            end
        else
            respond_to do |format|
                flash.now[:alert] = "Please enter a ticker symbol to search"
                format.js { render partial: 'users/result.js' }
                # render 'users/my_portfolio'
            end
        end
    end

    def update
        @stock = Stock.find(params[:stock])
        @stock.last_price = Stock.update_prices(@stock.ticker)
        @stock.save

        redirect_to my_portfolio_path
    
    end
    
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

    def create
        stock = Stock.check_db(params[:ticker])
        if stock.blank?
            stock = Stock.new_lookup(params[:ticker])
            stock.save
        end
        @user_stock = UserStock.create(user: current_user, stock: stock)
        flash[:notice] = "#{stock.name} is now being tracked"
        redirect_to my_portfolio_path
    end

    def destroy
        stock = Stock.find(params[:id])
        user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
        user_stock.destroy
        flash[:alert] = "You are no longer tracking #{stock.name}'s stocks"
        redirect_to my_portfolio_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

  def search
    if params[:friend].present?
        @friends = User.search(params[:friend])
        @friends = current_user.except_current_user(@friends)
        if @friends.present?
          respond_to do |format|
            format.js { render partial: 'users/friend_result.js' }
          end
        else
          respond_to do |format|
            flash.now[:alert] = "Cannot find any user with that name or email"
            format.js { render partial: 'users/friend_result.js' }
          end
        end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter an email id or name to search"
        format.js { render partial: 'users/friend_result.js' }
        # render 'users/my_portfolio'
      end
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/_list.html.erb
<div class="row pt-4">
    <div class="col-sm-9">
        <table class="table table-hover table-striped table-secondary">
            <thead>
                <tr>
                <th scope="col">Name</th>
                <th scope="col">Friends since</th>
                <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @friends.each do |friend| %>
                    <tr>
                    <td><%= friend.full_name %></td>
                    <td><%= time_ago_in_words(current_user.friend_since(friend.id)) %></td> 
                    <td>
                        <%= link_to "View Profile", user_path(friend), class: "btn btn-info" %>
                        <%= link_to "Unfriend", friendship_path(friend), method: :delete, data: {confirm: "Are you sure you want to unfriend #{friend.full_name}"}, class: "btn btn-danger" %>
                    </td>
                    </tr>
                <% end %>
            </tbody>
            </table>
    </div>
</div>

app/views/layouts/_flash_messages.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>

<% if flash.any? %>

    <% if flash[:notice] %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
            <%= notice %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>  
    <% end %>

    <% if flash[:alert] %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <%= alert %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div> 
    <% end %>

<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Finance Tracker", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <% if user_signed_in? %>
          <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
            <%= link_to 'My Portfolio', my_portfolio_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if request.path == my_friends_path %>">
            <%= link_to 'My Friends', my_friends_path, class: "nav-link" %>
          </li>
        <% end %>
      
        <!---
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        --->

      </ul>
      <% if user_signed_in? %>
        <%= form_tag search_stock_path, class: "d-flex me-auto", remote: true, method: :get do %>
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
        <% end %>
      <% end %>

      <ul class="nav navbar-nav navbar-right me-2 mb-2 mb-lg-0">
            <li class="navbar-item">
                <div class="btn-group" role="group" aria-label="Basic outlined example">
                    <% if user_signed_in? %>


                        <% if false %>
                            <%# To Implement %>
                            <button type="button" class="btn btn-outline-info dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <%= "(Admin)" if current_user[:admin] %> <%= current_user[:username] %>
                            </button>
                            <div class="dropdown-menu">
                                <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
                                <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
                                <%= link_to "Create an article", new_article_path, class: "dropdown-item" %>
                                <div class="dropdown-divider"></div>
                                <%= link_to "Delete account", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "This action will delete your account and all associated articles as well, are you sure you want to delete your account" } %>
                            </div>
                        <% end %>

                        <li class="nav-item dropdown pe-2">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <%= fa_icon 'user' %> <%= current_user.full_name %>
                          </a>
                          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                              <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                                <%= fa_icon 'edit' %> Edit Account
                              <% end %>  
                            </li>
                            <li>
                              <%= link_to my_friends_path, class: "dropdown-item" do %>
                                <%= fa_icon 'users' %> My Friends
                              <% end %>  
                            </li>
                          </ul>
                        </li>
                        
                        <% if false %>
                          <li class="nav-item text-light user-name">
                            <%= fa_icon 'user' %> <%= current_user.full_name %>
                          </li> 
                        <% end %>

                        <li class="nav-item">
                          <%= link_to "Logout", destroy_user_session_path, class: "btn btn-danger", method: :delete %>
                        </li>

                    <% else %>

                          <%= link_to "Login", new_user_session_path, class: "btn btn-outline-success" %>
                          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success" %>
          
                    <% end %>
                </div>            
            </li>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
    </div>

    <div class="container main-body">
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row pt-4">
    <div class="col-sm-9">
        <table class="table table-hover table-striped table-secondary">
            <thead>
                <tr>
                <th scope="col">Ticker</th>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @tracked_stocks.each do |stock| %>
                    <tr>
                    <th scope="row"><%= stock.ticker %></th>
                    <td><%= stock.name %></td>
                    <td><%= stock.last_price %></td>
                    <td>
                        <%= link_to "Update Prices", stocks_update_path(stock: stock.id), method: :post, class: "btn btn-info" %>
                        <% if current_user == @user %>
                            <%= link_to "Untrack", user_stock_path(stock), method: :delete, data: {confirm: "Are you sure you want to untrack #{stock.name}'s stock?"}, class: "btn btn-danger" %>
                        <% else %>
                            <% if current_user.can_track_stock?(stock.ticker.upcase) %>
                                <%= link_to "Track Stock", user_stocks_path(user: current_user, ticker: stock.ticker.upcase), class: "btn btn-outline-success ms-4", method: :post %>
                            <% else %>
                                <span class="badge bg-danger ms-4">
                                    You are already tracking
                                    <% if !current_user.under_stock_limit? %>
                                        10 stocks
                                    <% end %>
                                    <% if current_user.already_tracked?(stock.ticker.upcase) %>
                                        this stock
                                    <% end %>
                                </span>
                            <% end %>
                        <% end %>
                        
                    </td>
                    </tr>
                <% end %>
            </tbody>
            </table>
    </div>
</div>

app/views/users/_friend_result.html.erb
<div class="portfolio-result">
    <%= render 'layouts/flash_messages' %>
</div>

<% if @friends.present? %>
    <div class="card card-header portfolio-result">
        <table class="col-md-12">
            <tbody>
                <% @friends.each do |friend| %>
                    <tr>
                        <td class="pe-4"><strong>Name</strong>: <%= friend.full_name %></td>
                        <td class="ps-4"><strong>Email Id</strong>: <%= friend.email %></td>
                        <td>
                            <%= link_to "View Profile", user_path(friend), class: "btn btn-info ms-4" %>
                            <% if current_user.not_friends_with?(friend.id) %>
                                <%= link_to "Add Friend", friendships_path(friend: friend), method: :post, class: "btn btn-success ms-2" %>
                            <% else %>
                                <span class="badge bg-secondary ms-2">
                                    You are already friends with this user
                                </span>
                            <% end %>
                        </td>
                    </tr>
                <% end %>

            </tbody>
        </table>
    </div>
        
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/friend_result.html' %>'

app/views/users/_result.html.erb
<div class="portfolio-result">
    <%= render 'layouts/flash_messages' %>
</div>

<% if @stock %>
    <div class="card card-header portfolio-result">
        <strong>Symbol</strong>: <%= @stock.ticker.upcase %>
        <strong>Name</strong>: <%= @stock.name %>
        <strong>Price</strong>: <%= @stock.last_price %>

        <% if current_user.can_track_stock?(@stock.ticker.upcase) %>
            <%= link_to "Track Stock", user_stocks_path(user: current_user, ticker: @stock.ticker.upcase), class: "btn btn-outline-success ms-4", method: :post %>
        <% else %>
            <%# <%= link_to "Update Last Price", stocks_update_path(stock: @stock.ticker), method: :post, class: "btn btn-info ms-4" %> 
            <span class="badge bg-danger ms-2">
                You are already tracking
                <% if current_user.already_tracked?(@stock.ticker.upcase) %>
                    this stock
                <% elsif !current_user.under_stock_limit? %>
                    10 stocks
                <% end %>
            </span>
        <% end %>

    </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/result.html' %>'
<%# the j here stands for escape javascript and can also be written as escape_javascript() %>

app/views/users/my_friends.html.erb
<h1>My Friends</h1>

<div class="search-area">

    <h4>Search for your Friends</h4>
    <%= form_tag search_friend_path, remote: true, method: :get do %>

        <div class="form-group row">
            <div class="col-sm-9 no-padding-right">
                <%= text_field_tag :friend, params[:friend], placeholder: "Enter your friend's email id or name", autofocus: true, class: "form-control form-control-lg" %>
            </div>
            <div class="col-sm-3 no-padding-left">
                <%= button_tag type: :submit, class: "btn btn-outline-success btn-lg" do %>
                    <%= fa_icon 'search', text: 'Search' %>
                <% end %>
            </div>
        </div>

    <% end %>

    <div id="results">
    <%# id to handle the JS response %>
    </div>

    <% if !@friends.empty? %>
        <%= render 'friendships/list' %>
    <% end %>

</div>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class="search-area">

    <h4>Search Stocks</h4>
    <%= form_tag search_stock_path, remote: true, method: :get do %>

        <div class="form-group row">
            <div class="col-sm-9 no-padding-right">
                <%= text_field_tag :stock, params[:stock], placeholder: "Stock Ticker Symbol", autofocus: true, class: "form-control form-control-lg" %>
            </div>
            <div class="col-sm-3 no-padding-left">
                <%= button_tag type: :submit, class: "btn btn-outline-success btn-lg" do %>
                    <%= fa_icon 'search', text: 'Search' %>
                <% end %>
            </div>
        </div>

    <% end %>

    <div id="results">
    <%# id to handle the JS response %>
    </div>

    <% if !@tracked_stocks.empty? %>
        <%= render 'stocks/list' %>
    <% end %>

</div>

app/views/users/show.html.erb
<h1>User Details</h1>

<div class="card card-header portfolio-result">
    <table class="col-md-12">
        <tbody>
            <tr>
                <td class="pe-4"><strong>Name</strong>: <%= @user.full_name %></td>
                <td class="ps-4"><strong>Email Id</strong>: <%= @user.email %></td>
                <td>
                    <% if current_user.not_friends_with?(@user.id) %>
                        <%= link_to "Add Friend", friendships_path(friend: @user), method: :post, class: "btn btn-success ms-2" %>
                    <% else %>
                        <span class="badge bg-secondary ms-2">
                            You have been friends with this user since <%= time_ago_in_words(current_user.friend_since(@user)) %>
                        </span>
                    <% end %>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<% if !@tracked_stocks.empty? %>
    <%= render 'stocks/list' %>
<% else %>
    <p class="lead mt-4">This user is not tracking any stocks</p>
<% end %>

app/views/welcome/index.html.erb
<h2>This is the WELCOME page</h2>

<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>